# Generated by Django 2.2 on 2024-05-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20240507_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='data_type',
            new_name='detailing_type',
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('latitude', 'longitude', 'detailing_type')},
        ),
    ]
